### ISSUE TITLE
request to add RS-CLIP

### ISSUE THREAD

**Issue by lx709** [ZhanYang-nwpu/Awesome-Remote-Sensing-Multimodal-Large-Language-Model#2]
Hello @ZhanYang-nwpu, I believe the following paper fits your repo, please help to add it.

Li et al., RS-CLIP: Zero-shot remote sensing scene classification via contrastive vision-language supervision, JAG 2023.

**Comment by ZhanYang-nwpu** [comment]
> Hello @ZhanYang-nwpu, I believe the following paper fits your repo, please help to add it.
> 
> Li et al., RS-CLIP: Zero-shot remote sensing scene classification via contrastive vision-language supervision, JAG 2023.



OK, thank you very much for your attention, this paper has been added.
